site_name: xenondevs docs
site_url: https://xenondevs.xyz/docs/
repo_url: https://github.com/xenondevs/Docs
repo_name: xenondevs/Docs
copyright: Copyright &copy; 2022 xenondevs
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/xenondevs
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/hnEknVWvUe
theme:
  name: material
  logo: assets/logo.png
  palette:
    scheme: slate
  features:
    - content.tabs.link
    - navigation.tabs
    - content.code.annotate
  icon:
    repo: fontawesome/brands/github
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition
plugins:
  - i18n:
      default_language: en
      languages:
        en: English
        de: Deutsch
nav:
  - "Nova":
      - "Guide":
          - "Getting started": "nova/guide/index.md"
          - "Non Craftable": "nova/guide/non-craftable.md"
          - "Items and Machines": "nova/guide/items-machines.md"
            - "Machines": "nova/guide/machines.md"
            - "Items": "nova/guide/items.md"
      - "For Server Admins":
          - "Configs":
            - "Main Config": "nova/configs/main.md"
            - "Individual Configs": "nova/configs/individual.md"
          - "Recipes": "nova/configs/recipes.md"
      - "API":
          - "Getting Started": "nova/api/index.md"
          - "Protection": "nova/api/protection/protectionintegration.md"
          - "NovaMaterial": "nova/api/material/index.md"
          - "TileEntity":
              - "TileEntity": "nova/api/tileentity/tileentity.md"
              - "TileEntityManager": "nova/api/tileentity/tileentitymanager.md"
          - "Events":
              - "NovaLoadDataEvent": "nova/api/events/novaloaddataevent.md"
              - "ProtectionCheckEvent": "nova/api/events/protectioncheckevent.md"
              - "TileEntityBreakBlockEvent": "nova/api/events/tileentitybreakblockevent.md"
  - "ParticleLib":
      - "": 'wip.md'
